sudo: required
services:
  - docker
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta
      - docker-ce

language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"

jobs:
  include:
    - stage: docker push
      node_js: 8
      script:
        - docker build -t rightstuff/inv-ui .
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
          docker push rightstuff/inv-ui;
          fi

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install
  - ng build 

script:
  - ng test --single-run
